{
 "title": "HLF Performances Review",
 "description": "Overview of the most important Fabric, system and Docker container metrics. ",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "containergroup", "label": "Container Group", "query": { "query": "label_values(container_group)" } },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "server",
    "label": "Node",
    "query": {
     "query": "label_values(node_boot_time, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[$interval])) * 100)"
    }
   ]
  },
  {
   "title": "Total Memory Usage by all containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=~\".+\"}) - sum(container_memory_cache{name=~\".+\"})"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{name=~\".+\"})"
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min((node_filesystem_size_bytes - node_filesystem_free_bytes )/ node_filesystem_size_bytes)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  { "title": "Docker Containers Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Total CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (name)(rate(container_cpu_usage_seconds_total{name!~\"cadvisor|node-exporter|grafana|prometheus||\"}[$interval])) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Memory Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name!~\"cadvisor|node-exporter|grafana|prometheus||\"} - container_memory_cache{name!~\"cadvisor|node-exporter|grafana|prometheus||\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Usage memory",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name!~\"prometheus|cadvisor|grafana|node-exporter\", name=~\".+\"} - container_memory_cache{name!~\"prometheus|cadvisor|grafana|node-exporter\", name=~\".+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (name)(rate(container_cpu_usage_seconds_total{name!~\"cadvisor|node-exporter|grafana|prometheus||\"}[$interval])) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (container_memory_usage_bytes{name!~\"prometheus|cadvisor|grafana|node-exporter|\"}-container_memory_cache{name!~\"prometheus|cadvisor|grafana|node-exporter|\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Chaincode Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(job, chaincode) (rate(chaincode_shim_request_duration_sum{chaincode!~\"_lifecycle.*|cscc|qscc\"}[$interval])) / sum by(job, chaincode) (rate(chaincode_shim_request_duration_count{chaincode!~\"_lifecycle.*|cscc|qscc\"}[$interval]))",
     "legendFormat": " {{job}} {{chaincode}}"
    }
   ]
  },
  {
   "title": "Request Received",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without(channel,type) (rate(chaincode_shim_requests_received{chaincode!~\"_lifecycle.*|cscc|qscc\"}[$interval]))",
     "legendFormat": "{{job}} {{chaincode}}"
    }
   ]
  },
  {
   "title": "Requests Completed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (chaincode,job) (rate(chaincode_shim_requests_completed{chaincode!~\"_lifecycle.*|cscc|qscc\"}[$interval]))",
     "legendFormat": "{{job}} {{chaincode}}"
    }
   ]
  },
  { "title": "Endorser Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Successful Proposal Duration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without(channel, chaincode) (rate(endorser_proposal_duration_sum{chaincode!~\"cscc|qscc|_lifecycle.*\",success=\"true\"}[$interval])) / sum without(channel, chaincode) (rate(endorser_proposal_duration_count{chaincode!~\"cscc|qscc|_lifecycle.*\",success=\"true\"}[$interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Proposal Received",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(endorser_proposals_received[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Successful Proposals",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(endorser_successful_proposals[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Ledger Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Block Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without(channel) (rate(ledger_block_processing_time_sum[$interval])) / sum without(channel) (rate(ledger_block_processing_time_count[$interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Block  Storage Commit Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without(channel) (rate(ledger_blockstorage_commit_time_sum[$interval])) / sum without(channel) (rate(ledger_blockstorage_commit_time_count[$interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "StateDB Commit Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without(channel) (rate(ledger_statedb_commit_time_sum[$interval])) / sum without(channel) (rate(ledger_statedb_commit_time_count[$interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Blockchain height",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 70 },
   "targets": [
    { "expr": "ledger_blockchain_height", "legendFormat": "{{job}}" }
   ]
  }
 ]
}