#!/bin/bash

function createSeller() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/seller.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/seller.example.com/

  set -x
  fabric-ca-client enroll -u http://admin:adminpw@localhost:7054 --caname ca-seller --tls.certfiles "${PWD}/organizations/fabric-ca/seller/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-seller.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-seller.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-seller.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-seller.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/seller.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy seller's CA cert to seller's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/seller.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/seller/ca-cert.pem" "${PWD}/organizations/peerOrganizations/seller.example.com/msp/tlscacerts/ca.crt"

  # Copy seller's CA cert to seller's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/seller.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/seller/ca-cert.pem" "${PWD}/organizations/peerOrganizations/seller.example.com/tlsca/tlsca.seller.example.com-cert.pem"

  # Copy seller's CA cert to seller's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/seller.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/seller/ca-cert.pem" "${PWD}/organizations/peerOrganizations/seller.example.com/ca/ca.seller.example.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-seller --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/seller/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering peer1"
  set -x
  fabric-ca-client register --caname ca-seller --id.name peer1 --id.secret peer1pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/seller/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-seller --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/seller/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-seller --id.name selleradmin --id.secret selleradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/seller/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u http://peer0:peer0pw@localhost:7054 --caname ca-seller -M "${PWD}/organizations/peerOrganizations/seller.example.com/peers/peer0.seller.example.com/msp" --csr.hosts peer0.seller.example.com --tls.certfiles "${PWD}/organizations/fabric-ca/seller/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/seller.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/seller.example.com/peers/peer0.seller.example.com/msp/config.yaml"

  infoln "Generating the peer1 msp"
  set -x
  fabric-ca-client enroll -u http://peer1:peer1pw@localhost:7054 --caname ca-seller -M "${PWD}/organizations/peerOrganizations/seller.example.com/peers/peer1.seller.example.com/msp" --csr.hosts peer1.seller.example.com --tls.certfiles "${PWD}/organizations/fabric-ca/seller/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/seller.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/seller.example.com/peers/peer1.seller.example.com/msp/config.yaml"


  infoln "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u http://peer0:peer0pw@localhost:7054 --caname ca-seller -M "${PWD}/organizations/peerOrganizations/seller.example.com/peers/peer0.seller.example.com/tls" --enrollment.profile tls --csr.hosts peer0.seller.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/seller/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/seller.example.com/peers/peer0.seller.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/seller.example.com/peers/peer0.seller.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/seller.example.com/peers/peer0.seller.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/seller.example.com/peers/peer0.seller.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/seller.example.com/peers/peer0.seller.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/seller.example.com/peers/peer0.seller.example.com/tls/server.key"

  infoln "Generating the peer1-tls certificates"
  set -x
  fabric-ca-client enroll -u http://peer1:peer1pw@localhost:7054 --caname ca-seller -M "${PWD}/organizations/peerOrganizations/seller.example.com/peers/peer1.seller.example.com/tls" --enrollment.profile tls --csr.hosts peer1.seller.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/seller/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/seller.example.com/peers/peer1.seller.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/seller.example.com/peers/peer1.seller.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/seller.example.com/peers/peer1.seller.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/seller.example.com/peers/peer1.seller.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/seller.example.com/peers/peer1.seller.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/seller.example.com/peers/peer1.seller.example.com/tls/server.key"


  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u http://user1:user1pw@localhost:7054 --caname ca-seller -M "${PWD}/organizations/peerOrganizations/seller.example.com/users/User1@seller.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/seller/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/seller.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/seller.example.com/users/User1@seller.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u http://selleradmin:selleradminpw@localhost:7054 --caname ca-seller -M "${PWD}/organizations/peerOrganizations/seller.example.com/users/Admin@seller.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/seller/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/seller.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/seller.example.com/users/Admin@seller.example.com/msp/config.yaml"
}

function createBuyer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/buyer.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/buyer.example.com/

  set -x
  fabric-ca-client enroll -u http://admin:adminpw@localhost:8054 --caname ca-buyer --tls.certfiles "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-buyer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-buyer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-buyer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-buyer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/buyer.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy buyer's CA cert to buyer's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/buyer.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/buyer.example.com/msp/tlscacerts/ca.crt"

  # Copy buyer's CA cert to buyer's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/buyer.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/buyer.example.com/tlsca/tlsca.buyer.example.com-cert.pem"

  # Copy buyer's CA cert to buyer's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/buyer.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/buyer.example.com/ca/ca.buyer.example.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-buyer --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering peer1"
  set -x
  fabric-ca-client register --caname ca-buyer --id.name peer1 --id.secret peer1pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-buyer --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-buyer --id.name buyeradmin --id.secret buyeradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u http://peer0:peer0pw@localhost:8054 --caname ca-buyer -M "${PWD}/organizations/peerOrganizations/buyer.example.com/peers/peer0.buyer.example.com/msp" --csr.hosts peer0.buyer.example.com --tls.certfiles "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/buyer.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/buyer.example.com/peers/peer0.buyer.example.com/msp/config.yaml"

  infoln "Generating the peer1 msp"
  set -x
  fabric-ca-client enroll -u http://peer1:peer1pw@localhost:8054 --caname ca-buyer -M "${PWD}/organizations/peerOrganizations/buyer.example.com/peers/peer1.buyer.example.com/msp" --csr.hosts peer1.buyer.example.com --tls.certfiles "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/buyer.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/buyer.example.com/peers/peer1.buyer.example.com/msp/config.yaml"


  infoln "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u http://peer0:peer0pw@localhost:8054 --caname ca-buyer -M "${PWD}/organizations/peerOrganizations/buyer.example.com/peers/peer0.buyer.example.com/tls" --enrollment.profile tls --csr.hosts peer0.buyer.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/buyer.example.com/peers/peer0.buyer.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/buyer.example.com/peers/peer0.buyer.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/buyer.example.com/peers/peer0.buyer.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/buyer.example.com/peers/peer0.buyer.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/buyer.example.com/peers/peer0.buyer.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/buyer.example.com/peers/peer0.buyer.example.com/tls/server.key"

  infoln "Generating the peer1-tls certificates"
  set -x
  fabric-ca-client enroll -u http://peer1:peer1pw@localhost:8054 --caname ca-buyer -M "${PWD}/organizations/peerOrganizations/buyer.example.com/peers/peer1.buyer.example.com/tls" --enrollment.profile tls --csr.hosts peer1.buyer.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/buyer.example.com/peers/peer1.buyer.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/buyer.example.com/peers/peer1.buyer.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/buyer.example.com/peers/peer1.buyer.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/buyer.example.com/peers/peer1.buyer.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/buyer.example.com/peers/peer1.buyer.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/buyer.example.com/peers/peer1.buyer.example.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u http://user1:user1pw@localhost:8054 --caname ca-buyer -M "${PWD}/organizations/peerOrganizations/buyer.example.com/users/User1@buyer.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/buyer.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/buyer.example.com/users/User1@buyer.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u http://buyeradmin:buyeradminpw@localhost:8054 --caname ca-buyer -M "${PWD}/organizations/peerOrganizations/buyer.example.com/users/Admin@buyer.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/buyer.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/buyer.example.com/users/Admin@buyer.example.com/msp/config.yaml"
}

function createInspector {
	infoln "Enrolling the CA admin"
	mkdir -p organizations/peerOrganizations/inspector.example.com/

	export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/inspector.example.com/

  set -x
  fabric-ca-client enroll -u http://admin:adminpw@localhost:11054 --caname ca-inspector --tls.certfiles ${PWD}/organizations/fabric-ca/inspector/ca-cert.pem
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-inspector.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-inspector.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-inspector.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-inspector.pem
    OrganizationalUnitIdentifier: orderer' > ${PWD}/organizations/peerOrganizations/inspector.example.com/msp/config.yaml

	infoln "Registering peer0"
  set -x
	fabric-ca-client register --caname ca-inspector --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles ${PWD}/organizations/fabric-ca/inspector/tls-cert.pem
  { set +x; } 2>/dev/null

  infoln "Registering peer1"
  set -x
  fabric-ca-client register --caname ca-inspector --id.name peer1 --id.secret peer1pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/inspector/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-inspector --id.name user1 --id.secret user1pw --id.type client --tls.certfiles ${PWD}/organizations/fabric-ca/inspector/tls-cert.pem
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-inspector --id.name inspectoradmin --id.secret inspectoradminpw --id.type admin --tls.certfiles ${PWD}/organizations/fabric-ca/inspector/tls-cert.pem
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
	fabric-ca-client enroll -u http://peer0:peer0pw@localhost:11054 --caname ca-inspector -M ${PWD}/organizations/peerOrganizations/inspector.example.com/peers/peer0.inspector.example.com/msp --csr.hosts peer0.inspector.example.com --tls.certfiles ${PWD}/organizations/fabric-ca/inspector/tls-cert.pem
  { set +x; } 2>/dev/null

  cp ${PWD}/organizations/peerOrganizations/inspector.example.com/msp/config.yaml ${PWD}/organizations/peerOrganizations/inspector.example.com/peers/peer0.inspector.example.com/msp/config.yaml

  infoln "Generating the peer1 msp"
  set -x
  fabric-ca-client enroll -u http://peer1:peer1pw@localhost:11054 --caname ca-inspector -M "${PWD}/organizations/peerOrganizations/inspector.example.com/peers/peer1.inspector.example.com/msp" --csr.hosts peer1.inspector.example.com --tls.certfiles "${PWD}/organizations/fabric-ca/inspector/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/inspector.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/inspector.example.com/peers/peer1.inspector.example.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u http://peer0:peer0pw@localhost:11054 --caname ca-inspector -M ${PWD}/organizations/peerOrganizations/inspector.example.com/peers/peer0.inspector.example.com/tls --enrollment.profile tls --csr.hosts peer0.inspector.example.com --csr.hosts localhost --tls.certfiles ${PWD}/organizations/fabric-ca/inspector/tls-cert.pem
  { set +x; } 2>/dev/null

  cp ${PWD}/organizations/peerOrganizations/inspector.example.com/peers/peer0.inspector.example.com/tls/tlscacerts/* ${PWD}/organizations/peerOrganizations/inspector.example.com/peers/peer0.inspector.example.com/tls/ca.crt
  cp ${PWD}/organizations/peerOrganizations/inspector.example.com/peers/peer0.inspector.example.com/tls/signcerts/* ${PWD}/organizations/peerOrganizations/inspector.example.com/peers/peer0.inspector.example.com/tls/server.crt
  cp ${PWD}/organizations/peerOrganizations/inspector.example.com/peers/peer0.inspector.example.com/tls/keystore/* ${PWD}/organizations/peerOrganizations/inspector.example.com/peers/peer0.inspector.example.com/tls/server.key

  mkdir ${PWD}/organizations/peerOrganizations/inspector.example.com/msp/tlscacerts
  cp ${PWD}/organizations/peerOrganizations/inspector.example.com/peers/peer0.inspector.example.com/tls/tlscacerts/* ${PWD}/organizations/peerOrganizations/inspector.example.com/msp/tlscacerts/ca.crt

  mkdir ${PWD}/organizations/peerOrganizations/inspector.example.com/tlsca
  cp ${PWD}/organizations/peerOrganizations/inspector.example.com/peers/peer0.inspector.example.com/tls/tlscacerts/* ${PWD}/organizations/peerOrganizations/inspector.example.com/tlsca/tlsca.inspector.example.com-cert.pem

  mkdir ${PWD}/organizations/peerOrganizations/inspector.example.com/ca
  cp ${PWD}/organizations/peerOrganizations/inspector.example.com/peers/peer0.inspector.example.com/msp/cacerts/* ${PWD}/organizations/peerOrganizations/inspector.example.com/ca/ca.inspector.example.com-cert.pem

  infoln "Generating the peer1-tls certificates"
  set -x
  fabric-ca-client enroll -u http://peer1:peer1pw@localhost:11054 --caname ca-inspector -M ${PWD}/organizations/peerOrganizations/inspector.example.com/peers/peer1.inspector.example.com/tls --enrollment.profile tls --csr.hosts peer1.inspector.example.com --csr.hosts localhost --tls.certfiles ${PWD}/organizations/fabric-ca/inspector/tls-cert.pem
  { set +x; } 2>/dev/null

  cp ${PWD}/organizations/peerOrganizations/inspector.example.com/peers/peer1.inspector.example.com/tls/tlscacerts/* ${PWD}/organizations/peerOrganizations/inspector.example.com/peers/peer1.inspector.example.com/tls/ca.crt
  cp ${PWD}/organizations/peerOrganizations/inspector.example.com/peers/peer1.inspector.example.com/tls/signcerts/* ${PWD}/organizations/peerOrganizations/inspector.example.com/peers/peer1.inspector.example.com/tls/server.crt
  cp ${PWD}/organizations/peerOrganizations/inspector.example.com/peers/peer1.inspector.example.com/tls/keystore/* ${PWD}/organizations/peerOrganizations/inspector.example.com/peers/peer1.inspector.example.com/tls/server.key

  mkdir ${PWD}/organizations/peerOrganizations/inspector.example.com/msp/tlscacerts
  cp ${PWD}/organizations/peerOrganizations/inspector.example.com/peers/peer1.inspector.example.com/tls/tlscacerts/* ${PWD}/organizations/peerOrganizations/inspector.example.com/msp/tlscacerts/ca.crt

  mkdir ${PWD}/organizations/peerOrganizations/inspector.example.com/tlsca
  cp ${PWD}/organizations/peerOrganizations/inspector.example.com/peers/peer1.inspector.example.com/tls/tlscacerts/* ${PWD}/organizations/peerOrganizations/inspector.example.com/tlsca/tlsca.inspector.example.com-cert.pem

  mkdir ${PWD}/organizations/peerOrganizations/inspector.example.com/ca
  cp ${PWD}/organizations/peerOrganizations/inspector.example.com/peers/peer1.inspector.example.com/msp/cacerts/* ${PWD}/organizations/peerOrganizations/inspector.example.com/ca/ca.inspector.example.com-cert.pem

  
  infoln "Generating the user msp"
  set -x
	fabric-ca-client enroll -u http://user1:user1pw@localhost:11054 --caname ca-inspector -M ${PWD}/organizations/peerOrganizations/inspector.example.com/users/User1@inspector.example.com/msp --tls.certfiles ${PWD}/organizations/fabric-ca/inspector/tls-cert.pem
  { set +x; } 2>/dev/null

  cp ${PWD}/organizations/peerOrganizations/inspector.example.com/msp/config.yaml ${PWD}/organizations/peerOrganizations/inspector.example.com/users/User1@inspector.example.com/msp/config.yaml

  infoln "Generating the org admin msp"
  set -x
	fabric-ca-client enroll -u http://inspectoradmin:inspectoradminpw@localhost:11054 --caname ca-inspector -M ${PWD}/organizations/peerOrganizations/inspector.example.com/users/Admin@inspector.example.com/msp --tls.certfiles ${PWD}/organizations/fabric-ca/inspector/tls-cert.pem
  { set +x; } 2>/dev/null

  cp ${PWD}/organizations/peerOrganizations/inspector.example.com/msp/config.yaml ${PWD}/organizations/peerOrganizations/inspector.example.com/users/Admin@inspector.example.com/msp/config.yaml
}

function createOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/example.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/example.com

  set -x
  fabric-ca-client enroll -u http://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/example.com/msp/tlscacerts/tlsca.example.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem"

  infoln "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u http://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp" --csr.hosts orderer.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/config.yaml"

  infoln "Generating the orderer-tls certificates"
  set -x
  fabric-ca-client enroll -u http://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls" --enrollment.profile tls --csr.hosts orderer.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem"

  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u http://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/users/Admin@example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/example.com/users/Admin@example.com/msp/config.yaml"
}
